data_retrieval:
  max_num_workers: 30
google_cloud:
  project_id: ""
  pubsub:
    data_retrieval_topic_id: "retrieval-topic"
    data_retrieval_deadletter_topic_id: "retrieval-dead-letter-topic"
    data_retrieval_subscription_id: "retrieval-topic-sub"
    data_cleaning_topic_id: "cleaning-topic"
    data_cleaning_deadletter_topic_id: "cleaning-dead-letter-topic"
    data_cleaning_subscription_id: "cleaning-topic-sub"
    publish_timeout_in_seconds: 60
    max_num_received_messages: 30
    max_delivery_attempts: 5
    retry_deadline_in_seconds: 120
    ack_deadline_in_seconds: 120